module.exports = [
    { title: 'Async-Await in JavaScript', metatags: ['javascript', 'js', 'async', 'await', 'asynchronous', 'promises'] },
    { title: 'JavaScript Closures Explained', metatags: ['javascript', 'js', 'closures', 'scope', 'functions', 'lexical scoping'] },
    { title: 'Understanding the Event Loop', metatags: ['javascript', 'js', 'event loop', 'concurrency', 'asynchronous', 'event driven'] },
    { title: 'Functional Programming in JavaScript', metatags: ['javascript', 'js', 'functional programming', 'functions', 'immutable', 'first-class'] },
    { title: 'Object-Oriented JavaScript Techniques', metatags: ['javascript', 'js', 'object-oriented', 'prototypes', 'classes', 'inheritance'] },
    { title: 'Debugging JavaScript with Chrome DevTools', metatags: ['javascript', 'js', 'debugging', 'chrome devtools', 'browser', 'development'] },
    { title: 'Promises and Error Handling in JavaScript', metatags: ['javascript', 'js', 'promises', 'error handling', 'async', 'catch'] },
    { title: 'Implementing JavaScript ES6 Features', metatags: ['javascript', 'es6', 'features', 'syntax', 'arrow functions', 'template literals'] },
    { title: 'JavaScript Modules and Import/Export Syntax', metatags: ['javascript', 'js', 'modules', 'import', 'export', 'es6'] },
    { title: 'Building Single Page Applications with JavaScript', metatags: ['javascript', 'js', 'single page application', 'spa', 'frameworks', 'frontend'] },
    { title: 'JavaScript Memory Management and Garbage Collection', metatags: ['javascript', 'js', 'memory management', 'garbage collection', 'performance', 'leaks'] },
    { title: 'Asynchronous JavaScript with Callbacks and Promises', metatags: ['javascript', 'js', 'asynchronous', 'callbacks', 'promises', 'async/await'] },
    { title: 'JavaScript\'s Prototype Chain and Inheritance', metatags: ['javascript', 'js', 'prototype', 'inheritance', 'chain', 'objects']},
    { title: 'DOM Manipulation and Event Handling in JavaScript', metatags: ['javascript', 'js', 'DOM', 'events', 'manipulation', 'web'] },
    { title: 'Understanding "this" Keyword in JavaScript', metatags: ['javascript', 'js', 'this', 'context', 'scope', 'functions'] },
    { title: 'Working with JSON in JavaScript', metatags: ['javascript', 'js', 'JSON', 'data', 'AJAX', 'web'] },
    { title: 'State Management in JavaScript Applications', metatags: ['javascript', 'js', 'state management', 'reactive', 'vue', 'redux'] },
    { title: 'JavaScript Testing Frameworks and Libraries', metatags: ['javascript', 'js', 'testing', 'jest', 'mocha', 'unit testing'] },
    { title: 'Web APIs and JavaScript: Fetch, Web Workers, and Service Workers', metatags: ['javascript', 'js', 'web api', 'fetch', 'web workers', 'service workers'] },
    { title: 'JavaScript Animation Techniques and Libraries', metatags: ['javascript', 'js', 'animation', 'canvas', 'svg', 'libraries'] },
    { title: 'Responsive Design with JavaScript and CSS', metatags: ['javascript', 'js', 'responsive design', 'css', 'media queries', 'mobile'] },
    { title: 'Building Real-Time Web Applications with JavaScript', metatags: ['javascript', 'js', 'real-time', 'websockets', 'socket.io', 'applications'] },
    { title: 'SEO Considerations in JavaScript-Rendered Websites', metatags: ['javascript', 'js', 'SEO', 'rendering', 'web development', 'performance'] },
    { title: 'Best Practices for Writing Clean JavaScript Code', metatags: ['javascript', 'js', 'best practices', 'clean code', 'standards', 'readable'] },
    { title: 'Memory Leaks and Performance Optimization in JavaScript', metatags: ['javascript', 'js', 'memory leaks', 'performance', 'optimization', 'profiling'] },
    { title: 'JavaScript Design Patterns and Code Organization', metatags: ['javascript', 'js', 'design patterns', 'code organization', 'architecture', 'best practices']}
];
